# Install script for directory: /home/gon/dev/libgdt/gdt

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_sistema.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gdt.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_guiboton.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_guibarra.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_nodo.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_gui.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_escenario.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_luz.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_sistemamatematicas.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_textura.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_camara.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_agua.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_archivo.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_cartelera.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_colisiones3d.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_controlesprediseniados.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_cuerpo.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_fundido.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_guidialogoabrir.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_guiedicion.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_guiimagen.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_guimenu.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_guitexto.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_guiventana.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_listaarchivos.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_malla.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_material_nwtno.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_musik.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_nwtno.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_panorama.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_particula.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_sistemalua.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_sistemasonido.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_sonido3d.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_sonido.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_terreno.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gd_xml.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gdt" TYPE FILE FILES "/home/gon/dev/libgdt/gdt/gdt_m.h")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE SHARED_LIBRARY FILES "/home/gon/dev/libgdt/gdt/CMakeFiles/CMakeRelink.dir/libgdt.so")
