#BUSCAR CABECERAS NEWTON
FIND_PATH(NEWTON_INCLUDE_DIR NAMES Newton.h
	PATHS
	$ENV{NEWTONDIR}/include
	/usr/local/include/newton
	/usr/local/include/Newton
	/usr/local/include/
	/usr/include/newton
	/usr/include/Newton
	/usr/include
	)

# BUSCAR LIBRERIA NEWTON
FIND_LIBRARY(NEWTON_LIBRARY NAMES Newton
	PATHS
	$ENV{NEWTONDIR}/lib
	$ENV{NEWTONDIR}/libs
	/usr/local/lib
	/usr/lib
	/sw/lib
	/opt/local/lib
	/opt/csw/lib
	/opt/lib
	)

IF(NOT NEWTON_LIBRARY)
	MESSAGE("NO SE HA ENCONTRADO LA BIBLIOTECA NEWTON")
ENDIF(NOT NEWTON_LIBRARY)

IF(NOT NEWTON_INCLUDE_DIR)
	MESSAGE("NO SE HAN ENCONTRADO CABECERAS DE NEWTON")
ENDIF(NOT NEWTON_INCLUDE_DIR)

SET(FISICA_FOUND "NO")
IF(NEWTON_INCLUDE_DIR AND NEWTON_LIBRARY)
   SET(FISICA_FOUND "YES")
ENDIF(NEWTON_INCLUDE_DIR AND NEWTON_LIBRARY)