// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_CARTELERA_H
#define GD_CARTELERA_H

#include "gd_nodo.h" // inheriting class's header file
#include "gd_escenario.h"
// No description
class GD_Cartelera : public GD_Nodo
{
	public:
		// class constructor
		GD_Cartelera();
		// class destructor
		~GD_Cartelera();
		
		IBillboardSceneNode* nodb;
		
		  void Crear(float tamx, float tamy, char* filename);
		  void CrearColision( GD_Escenario scen,float radiox, float radioy,float radioz,float transx,float transy,float transz,float grax,float gray, float graz);
};

#endif // GD_CARTELERA_H
