// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_ESCENARIO_H
#define GD_ESCENARIO_H

#include "gd_nodo.h" // inheriting class's header file

// No description
class GD_Escenario : public GD_Nodo
{
	public:
		// class constructor
		GD_Escenario();
		// class destructor
		~GD_Escenario();
		
          void CargarBSP(char *filenamePK3, char *filenameBSP);
          void Cargar(char *filename);

          IAnimatedMesh* mesh;
          IMesh* meshs;
          ITriangleSelector* selector;
          ITriangleSelector* RetornarDatos();
};

#endif // GD_ESCENARIO_H
