// Class automatically generated by Dev-C++ New Class wizard

#include "gd_fundido.h" // class's header file

// class constructor
GD_Fundido::GD_Fundido()
{
	// insert your code here
}

// class destructor
GD_Fundido::~GD_Fundido()
{
	// insert your code here
}

void GD_Fundido::Crear()
{

    RegistrarDevice(GD_Sistema::device);
    
    IVideoDriver* driver = midevice->getVideoDriver();
    IGUIEnvironment* guienv = midevice->getGUIEnvironment();
    
     //fundido=guienv->addInOutFader(rect<s32>(0,0,TamPantalla.Width, TamPantalla.Height), 0, -1);
     fundido=guienv->addInOutFader();
     
      guiele = fundido;
}
/*
void GD_Fundido::Crear( int x1, int y1, int x2, int y2)
{

    RegistrarDevice(GD_Sistema::device);
    
    IVideoDriver* driver = midevice->getVideoDriver();
    IGUIEnvironment* guienv = midevice->getGUIEnvironment();
    
    rect<s32> rec(x1,y1,x2,y2);
    
     fundido = guienv->addInOutFader(rec, 0, -1);
      
      guiele = fundido;
}
*/

void GD_Fundido::Color( int r, int g, int b)
{
     fundido->setColor(video::SColor(0, r, g, b) );
}

void GD_Fundido::FundirHaciaDentro(int tiempo)
{
     fundido->fadeIn(tiempo);
}

void GD_Fundido::FundirHaciaFuera(int tiempo)
{
     fundido->fadeOut(tiempo);
}

bool GD_Fundido::Terminado(void)
{
     fundido->isReady();
}
