// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_FUNDIDO_H
#define GD_FUNDIDO_H

#include "gd_gui.h" // inheriting class's header file

#include "gd_sistema.h"
/*
 * Para hacer fundidos de pantalla
 */
class GD_Fundido : public GD_gui
{
	public:
		// class constructor
		GD_Fundido();
		// class destructor
		~GD_Fundido();
		
		IGUIInOutFader* fundido;
		
		void Crear(void);
	//	void Crear( int x1, int y1, int x2, int y2);
		void Color(int r, int g, int b);
		void FundirHaciaDentro(int tiempo);
		void FundirHaciaFuera(int tiempo);
		bool Terminado(void);
        		
};

#endif // GD_FUNDIDO_H
