// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_GUIMENU_H
#define GD_GUIMENU_H

#include "gd_gui.h" // inheriting class's header file

#include "gd_sistema.h"
/*
 * GUI Menu y SubMenu
 */
class GD_GuiMenu : public GD_gui
{
	public:
		// class constructor
		GD_GuiMenu();
		GD_GuiMenu(IGUIContextMenu* SubMenu);
		// class destructor
		~GD_GuiMenu();

		int MenuID;

		IGUIContextMenu* menu;
		IGUIContextMenu* submenu; /** NUEVO **/


		void Crear(IGUIElement* padre=0);

		void InsertarOpcion(wchar_t * texto, bool bsubmenu,int nID, bool activado); /** MODIFICADO **/

		IGUIContextMenu* SubMenu(int  nID);

		void AbrirSubMenu(int iNivel,bool bPadre_es_Menu); /** NUEVO **/
		void InsertarSubMenu(wchar_t * texto, int nID,bool activado, bool bsubmenu);/** NUEVO **/

		void InsertarSeparador(void);

		void CambiarTextoOpcion(int nID, const wchar_t* texto, bool bPadre_es_Menu);
		const wchar_t* RetornarTextoOpcion(int nID);

		void OpcionActivada(int nID, bool activado);
		bool OpcionEstaActivada(int nID);

		int Seleccionado();

};

#endif // GD_GUIMENU_H
