// Class automatically generated by Dev-C++ New Class wizard

#include "gd_guiboton.h" // class's header file

// class constructor
GD_GuiBoton::GD_GuiBoton()
{
	// insert your code here
}

// class destructor
GD_GuiBoton::~GD_GuiBoton()
{
	// insert your code here
}

void GD_GuiBoton::Crear(int x1, int y1, int x2, int y2,IGUIElement* padre)
{

    RegistrarDevice(GD_Sistema::device);
    
    IVideoDriver* driver = midevice->getVideoDriver();
    IGUIEnvironment* guienv = midevice->getGUIEnvironment();
    
     boton=guienv->addButton(rect<s32>(x1,y1,x2,y2),padre, GD_Sistema::ContadorElementosGui++);

     
      guiele = boton;
}

void GD_GuiBoton::Crear(int x1, int y1, int x2, int y2, wchar_t * texto, IGUIElement* padre)
{    
    RegistrarDevice(GD_Sistema::device);
    
    IVideoDriver* driver = midevice->getVideoDriver();
    IGUIEnvironment* guienv = midevice->getGUIEnvironment();
    
     boton=guienv->addButton(rect<s32>(x1,y1,x2,y2),padre, GD_Sistema::ContadorElementosGui++);
     
     boton->setText(texto);
     
     guiele = boton;
}

void GD_GuiBoton::CrearConImagen(int x1, int y1, int x2, int y2, char* filename_boton_normal ,char* filename_boton_presionado , IGUIElement* padre)
{

    RegistrarDevice(GD_Sistema::device);
    
    IVideoDriver* driver = midevice->getVideoDriver();
    IGUIEnvironment* guienv = midevice->getGUIEnvironment();
    
     boton=guienv->addButton(rect<s32>(x1,y1,x2,y2),padre, GD_Sistema::ContadorElementosGui++);
 
     boton->setImage(driver->getTexture(filename_boton_normal));
     boton->setPressedImage(driver->getTexture(filename_boton_presionado)); 
     
      guiele = boton;
}
	

