// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_GUIDIALOGOABRIR_H
#define GD_GUIDIALOGOABRIR_H

#include "gd_gui.h" // inheriting class's header file

#include "gd_sistema.h"
/*
 * GUI Dialogo de Abrir
 */
class GD_GuiDialogoAbrir : public GD_gui
{
	public:
		// class constructor
		GD_GuiDialogoAbrir();
		// class destructor
		~GD_GuiDialogoAbrir();
		
		IGUIFileOpenDialog* opendlg;
		
		void Crear(wchar_t * titulo, bool modal, IGUIElement* padre=0);
		
};

#endif // GD_GUIDIALOGOABRIR_H
