// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_GUIEDICION_H
#define GD_GUIEDICION_H

#include "gd_gui.h" // inheriting class's header file

#include "gd_sistema.h"
/*
 * GUI Cuadro de Edici&oacute;n (EditBox)
 */
class GD_GuiEdicion : public GD_gui
{
	public:
		// class constructor
		GD_GuiEdicion();
		// class destructor
		~GD_GuiEdicion();
		
		IGUIEditBox* editbox;
		
		void Crear(int x1, int y1, int x2, int y2, wchar_t * texto, bool borde, IGUIElement* padre=0);
		void CaracteresMaximo(int max);
		int RetornarCaracteresMaximo(void);
};

#endif // GD_GUIEDICION_H
