// Class automatically generated by Dev-C++ New Class wizard

#include "gd_guiedicion.h" // class's header file

// class constructor
GD_GuiEdicion::GD_GuiEdicion()
{
	// insert your code here
}

// class destructor
GD_GuiEdicion::~GD_GuiEdicion()
{
	// insert your code here
}

void GD_GuiEdicion::Crear(int x1, int y1, int x2, int y2, wchar_t * texto, bool borde,IGUIElement* padre)
{

    RegistrarDevice(GD_Sistema::device);
    
    IVideoDriver* driver = midevice->getVideoDriver();
    IGUIEnvironment* guienv = midevice->getGUIEnvironment();
    
     editbox=guienv->addEditBox(texto, rect<s32>(x1,y1,x2,y2),borde,padre, GD_Sistema::ContadorElementosGui++);
      guiele = editbox;
}

// Poner 0 para infinito
void GD_GuiEdicion::CaracteresMaximo( int max )
{
     editbox->setMax(max);
}

int GD_GuiEdicion::RetornarCaracteresMaximo( void )
{
     return editbox->getMax();
}
