// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_SONIDO3D_H
#define GD_SONIDO3D_H

/*
 * No description
 */
#include <stdio.h>
#include <iostream>
#include <stdlib.h>
#include <al.h>
#include <alc.h>
#include <alut.h>
#include <ogg.h>
#include <vorbisfile.h>


using namespace std;

class GD_Sonido3D
{
    public:
        GD_Sonido3D();
        ~GD_Sonido3D();
    private:
        ALuint SBuffer;
        ALuint SSource;
        ALfloat SSourcePos[3];
        ALfloat SSourceVel[3];
        char SCargado;
        
        //para ogg
        /*ALuint buffers[2];
        FILE*           oggFile;
        OggVorbis_File  oggStream;
        vorbis_info*    vorbisInfo;
        vorbis_comment* vorbisComment;
        ALenum format;*/

    public:
        char Cargar(char *);
        //char CargarOgg(char *archivo);
        char CargarOGG(char *);
        void Descargar();
        void Reproducir();
        void Pausa();
        void Detener();
        void Rebobinar();
        void Play();
        void Pause();
        void Stop();
        void Rewind();
        void Bucle(char);
        void RelativoOyente(char);
        void VolumenMaximo(float);
        void VolumenMinimo(float);
        void ReferenciaDistancia(float);
        void FactorRolloff(float);
        void DistanciaMaxima(float);
        void Tono(float);
        int Estado();
        void Posicionar(float, float, float);
        void Velocidad(float, float, float);
};


#endif // GD_SONIDO3D_H
