// Class automatically generated by Dev-C++ New Class wizard

#include "gd_cartelera.h" // class's header file

// class constructor
GD_Cartelera::GD_Cartelera()
{
	// insert your code here
}

// class destructor
GD_Cartelera::~GD_Cartelera()
{
	// insert your code here
}


void GD_Cartelera::Crear(float tamx, float tamy, char* filename)
{
    
    RegistrarDevice(GD_Sistema::device);
    ISceneManager* mismgr=GD_Sistema::device->getSceneManager();


    
     nodb = mismgr->addBillboardSceneNode(0, core::dimension2d<f32>(tamx, tamy));
	 
	 nodon = nodb;
  
     if(!nodon) printf("ERROR: No se pudo Crear Cartelera.\n");
	  
	 nodon->setMaterialFlag(video::EMF_LIGHTING, false);
	 nodon->setMaterialType(video::EMT_TRANSPARENT_ADD_COLOR);
	 
	 Texturizar(filename);	 
}

void GD_Cartelera::CrearColision( GD_Escenario scen,float radiox, float radioy,float radioz,float transx,float transy,float transz,float grax,float gray, float graz)
{

    ITriangleSelector* selector = scen.RetornarDatos();

    ISceneManager* mismgr=midevice->getSceneManager();

	scene::ISceneNodeAnimator* anim = mismgr->createCollisionResponseAnimator(
		selector, nodon, core::vector3df(radiox,radioy,radioz),
		core::vector3df(transx,transy,transz),
		core::vector3df(grax,gray,graz));
	nodon->addAnimator(anim);
	//anim->drop();
}
