// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_GUI_H
#define GD_GUI_H

#include <irrlicht.h>

using namespace irr;
using namespace core;
using namespace scene;
using namespace video;
using namespace io;
using namespace gui;
/*
 * Funciones comunes entre los objetos GUI
 */


// No description
class GD_gui
{
	public:
		// class constructor
		GD_gui();
		// class destructor
		~GD_gui();

      IrrlichtDevice *midevice;

		IGUISkin* skin;
		IGUIFont* fuente;
		IGUIEnvironment* guienv;
		IGUIElement* guiele;


      void RegistrarDevice(	IrrlichtDevice *device );

		bool EstaActivado();
		bool EstaVisible();

		void Posicionar(int x, int y);
		void Posicionar(position2d<s32> pos);
		//Añadido--------------------------------
		void Mover(int x, int y);
		//---------------------------------------

		void Activado(bool estado);


		void Texto(const wchar_t *text);
		const wchar_t* RetornarTexto(void);

      void Visible(bool estado);

      int ID(void);

      IGUIElement* Elemento(void);

      void AdoptarHijo(IGUIElement* hijo);

      void Destruir(void);


      //Retornos
      position2d<s32> Posicion();
      int PosicionX();
      int PosicionY();
      position2d<s32> Centro();
      int CentroX();
      int CentroY();
      dimension2d<s32> Tamanio();
      int Ancho();
      int Alto();
      position2d<s32> EsquinaSuperiorIzquierda();
      int EsquinaSuperiorIzquierdaX();
      int EsquinaSuperiorIzquierdaY();
      position2d<s32> EsquinaInferiorDerecha();
      int EsquinaInferiorDerechaX();
      int EsquinaInferiorDerechaY();
      bool EsPuntoInterno(position2d<s32> punto);
      bool EsPuntoInterno(int x,int y);
      bool Colision(rect<s32> Rectangulo);
      bool Colision(IGUIElement* guiElemento);

};

#endif // GD_GUI_H
