// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_GUIIMAGEN_H
#define GD_GUIIMAGEN_H

#include "gd_gui.h" // inheriting class's header file

#include "gd_sistema.h"
/*
 * GUI Imagen
 */
class GD_GuiImagen : public GD_gui
{
	public:
      IVideoDriver* driver;
      ITexture* textura;
      dimension2d< s32 > tam;
		// class constructor
		GD_GuiImagen();
		// class destructor
		~GD_GuiImagen();

        IGUIImage* img;

        void Cargar(char *filename);
        void UsarCanalAlpha(bool uso);

        void Visible(bool estado);
};

#endif // GD_GUIIMAGEN_H
