// Class automatically generated by Dev-C++ New Class wizard

#include "gd_guimenu.h" // class's header file
// class constructor
GD_GuiMenu::GD_GuiMenu()
{
	// insert your code here
}

GD_GuiMenu::GD_GuiMenu(IGUIContextMenu* SubMenu)
{
	menu = SubMenu;
}

// class destructor
GD_GuiMenu::~GD_GuiMenu()
{
	// insert your code here
}

void GD_GuiMenu::Crear(IGUIElement* padre)
{
    RegistrarDevice(GD_Sistema::device);

    IVideoDriver* driver = midevice->getVideoDriver();
    IGUIEnvironment* guienv = midevice->getGUIEnvironment();

    MenuID=GD_Sistema::ContadorElementosGui++;
    menu=guienv->addMenu(padre, MenuID);

    guiele = menu;

}

void GD_GuiMenu::InsertarOpcion(wchar_t * texto, bool bsubmenu = false, int nID=-1, bool activado=true) /** MODIFICADO **/
{
   menu->addItem(texto,nID,activado,bsubmenu);
}

void GD_GuiMenu::InsertarSeparador(void)
{
    menu->addSeparator();
}

IGUIContextMenu* GD_GuiMenu::SubMenu(int  nID)
{
    return menu->getSubMenu(nID);
}

void GD_GuiMenu::AbrirSubMenu(int iNivel,bool bPadre_es_Menu=true) /** NUEVO **/
{
   if(bPadre_es_Menu==true)
   {
      submenu = menu->getSubMenu(iNivel);
   }
   else
   {
      submenu = submenu->getSubMenu(iNivel);
   }
}

void GD_GuiMenu::InsertarSubMenu(wchar_t * texto, int nID,bool activado=true, bool bsubmenu = false) /** NUEVO **/
{

   submenu->addItem(texto,nID,activado,bsubmenu);

}

void GD_GuiMenu::CambiarTextoOpcion(int nID, const wchar_t* texto, bool bPadre_es_Menu=true)
{
   if(bPadre_es_Menu=true)
   {
      menu->setItemText(nID, texto);
   }
   else
   {
      submenu->setItemText(nID,texto);
   }

}

const wchar_t* GD_GuiMenu::RetornarTextoOpcion(int nID)
{
      return menu->getItemText(nID);
}

void GD_GuiMenu::OpcionActivada(int nID, bool activado)
{
     menu->setItemEnabled(nID, activado);
}

bool GD_GuiMenu::OpcionEstaActivada(int nID)
{
     return menu->isItemEnabled(nID);
}

int GD_GuiMenu::Seleccionado()
{
   return 0;
}

