// Class automatically generated by Dev-C++ New Class wizard

#include "gd_guiventana.h" // class's header file

// class constructor
GD_GuiVentana::GD_GuiVentana()
{
	// insert your code here
}

// class destructor
GD_GuiVentana::~GD_GuiVentana()
{
	// insert your code here
}

void GD_GuiVentana::Crear(int x1, int y1, int x2, int y2, wchar_t * texto, bool modal, IGUIElement* padre)
{

    RegistrarDevice(GD_Sistema::device);
    
    IVideoDriver* driver = midevice->getVideoDriver();
    IGUIEnvironment* guienv = midevice->getGUIEnvironment();
    
     ventana=guienv->addWindow(rect<s32>(x1,y1,x2,y2),modal, texto, padre, GD_Sistema::ContadorElementosGui++);
     
     // Provisional. Desactivamos y ocultamos el Botón de Cerrar.
     // Porque si la ventana adopta hijos de un error al cerrarse
     ventana->getCloseButton()->setEnabled(false); 
     ventana->getCloseButton()->setVisible(false); 
     
      guiele = ventana;
}
