// Class automatically generated by Dev-C++ New Class wizard

#include "gd_guidialogoabrir.h" // class's header file

// class constructor
GD_GuiDialogoAbrir::GD_GuiDialogoAbrir()
{
	// insert your code here
}

// class destructor
GD_GuiDialogoAbrir::~GD_GuiDialogoAbrir()
{
	// insert your code here
}

void GD_GuiDialogoAbrir::Crear(wchar_t * titulo, bool modal, IGUIElement* padre)
{

    RegistrarDevice(GD_Sistema::device);
    
    IVideoDriver* driver = midevice->getVideoDriver();
    IGUIEnvironment* guienv = midevice->getGUIEnvironment();
    
     opendlg=guienv->addFileOpenDialog(titulo, modal, padre, GD_Sistema::ContadorElementosGui++);
      guiele = opendlg;
}

