// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_GUIBOTON_H
#define GD_GUIBOTON_H

#include "gd_gui.h" // inheriting class's header file

#include "gd_sistema.h"
/*
 * GUI Botones 
 */
class GD_GuiBoton : public GD_gui
{
	public:
		// class constructor
		GD_GuiBoton();
		// class destructor
		~GD_GuiBoton();
		
		IGUIButton* boton;

         void Crear(int x1, int y1, int x2, int y2, IGUIElement* padre=0); 
         void Crear(int x1, int y1, int x2, int y2, wchar_t * texto, IGUIElement* padre=0);
         void CrearConImagen(int x1, int y1, int x2, int y2, char* filename_boton_normal ,char* filename_boton_presionado, IGUIElement* padre=0);
};

#endif // GD_GUIBOTON_H
