// Class automatically generated by Dev-C++ New Class wizard

#include "gd_guibarra.h" // class's header file

// class constructor
GD_GuiBarra::GD_GuiBarra()
{
	// insert your code here
}

// class destructor
GD_GuiBarra::~GD_GuiBarra()
{
	// insert your code here
}

void GD_GuiBarra::CrearHorizontal(int x1, int y1, int x2, int y2, IGUIElement* padre)
{

    RegistrarDevice(GD_Sistema::device); 
    
    IVideoDriver* driver = midevice->getVideoDriver();
    IGUIEnvironment* guienv = midevice->getGUIEnvironment();
    
     barra=guienv->addScrollBar(true, rect<s32>(x1,y1,x2,y2),padre, GD_Sistema::ContadorElementosGui++);
     
      guiele = barra;
}

void GD_GuiBarra::CrearVertical(int x1, int y1, int x2, int y2,IGUIElement* padre)
{

    RegistrarDevice(GD_Sistema::device); 
    
    IVideoDriver* driver = midevice->getVideoDriver();
    IGUIEnvironment* guienv = midevice->getGUIEnvironment();
    
     barra=guienv->addScrollBar(false, rect<s32>(x1,y1,x2,y2),padre, GD_Sistema::ContadorElementosGui++);
     
      guiele = barra;
}

void GD_GuiBarra::MaximoValor(int maximo)
{
     barra->setMax(maximo);
}

int GD_GuiBarra::Posicion(void)
{
     barra->getPos();
}

void GD_GuiBarra::Posicionar(int posicion)
{
     barra->setPos(posicion);
}

