// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_LISTAARCHIVOS_H
#define GD_LISTAARCHIVOS_H

#include "gd_sistema.h"
/*
 * Lista de archivos de un directorio
 */
class GD_ListaArchivos
{
	public:
		// class constructor
		GD_ListaArchivos();
		// class destructor
		~GD_ListaArchivos();
		
		IFileSystem* FileSystem;
		IFileList* FileList;
		
		void Crear(void);
		
		int Numero(void);
		
		const c8* Nombre(int id);
		const c8* NombreCompleto(int id);
		
		bool EsDirectorio(int id);
};

#endif // GD_LISTAARCHIVOS_H
