// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_PANORAMA_H
#define GD_PANORAMA_H

#include "gd_nodo.h" // inheriting class's header file

// No description
class GD_Panorama : public GD_Nodo
{
	public:
		// class constructor
		GD_Panorama();
		// class destructor
		~GD_Panorama();
		
         void CrearCubico(char* up, char* down, char* left, char* right, char* front,char* back);
         void CrearDomo(char* texturadomo, int hres, int vres, int texporc, int esfporc);       
};

#endif // GD_PANORAMA_H
