// Class automatically generated by Dev-C++ New Class wizard

#include "gd_panorama.h" // class's header file

// class constructor
GD_Panorama::GD_Panorama()
{
	// insert your code here
}

// class destructor
GD_Panorama::~GD_Panorama()
{
	// insert your code here
}


void GD_Panorama::CrearCubico(char* up, char* down, char* left, char* right, char* front,char* back)
{
    
    RegistrarDevice(GD_Sistema::device);
    ISceneManager* mismgr=GD_Sistema::device->getSceneManager();



     mismgr->getVideoDriver()->setTextureCreationFlag(video::ETCF_CREATE_MIP_MAPS, false);

	nodon = mismgr->addSkyBoxSceneNode(
		mismgr->getVideoDriver()->getTexture(up),
		mismgr->getVideoDriver()->getTexture(down),
		mismgr->getVideoDriver()->getTexture(left),
		mismgr->getVideoDriver()->getTexture(right),
		mismgr->getVideoDriver()->getTexture(front),
		mismgr->getVideoDriver()->getTexture(back));
		
    if(!nodon) printf("ERROR: No se pudo Crear Panorama Cubico.\n"); 

	mismgr->getVideoDriver()->setTextureCreationFlag(video::ETCF_CREATE_MIP_MAPS, true);
	
	
}


void GD_Panorama::CrearDomo(char* texturadomo, int hres, int vres, int texporc, int esfporc)
{
    RegistrarDevice(GD_Sistema::device);
    ISceneManager* mismgr=GD_Sistema::device->getSceneManager();

    float texpor = texporc/100;
    float esfpor = esfporc/50;    
    
    if(texpor>1) texpor=1;
    if(esfpor>2) texpor=2;
    

    mismgr->getVideoDriver()->setTextureCreationFlag(video::ETCF_CREATE_MIP_MAPS, false);

	nodon = mismgr->addSkyDomeSceneNode(mismgr->getVideoDriver()->getTexture(texturadomo), 
                                        hres,
                                        vres,
                                        texpor,
                                        esfpor);

    if(!nodon) printf("ERROR: No se pudo Crear Panorama Domo.\n"); 


	mismgr->getVideoDriver()->setTextureCreationFlag(video::ETCF_CREATE_MIP_MAPS, true);


}
