// Class automatically generated by Dev-C++ New Class wizard

#ifndef GD_SONIDO_H
#define GD_SONIDO_H

#include "gd_sonido3d.h" // inheriting class's header file

/*
 * No description
 */
class GD_Sonido : public GD_Sonido3D
{
	public:
		// class constructor
		GD_Sonido();
		// class destructor
		~GD_Sonido();
		
		char Cargar(char *);
        void Descargar();
        void Reproducir();
        void Pausa();
        void Detener();
        void Rebobinar();
        void Play();
        void Pause();
        void Stop();
        void Rewind();
        void Bucle(char);
        void Volumen(int);
        //void FactorRolloff(float);
        void Pan(float);
        void Tono(float);
        int Estado();
};

#endif // GD_SONIDO_H
