// Class automatically generated by Dev-C++ New Class wizard

#include "gd_terreno.h" // class's header file

// class constructor
GD_Terreno::GD_Terreno()
{
	// insert your code here
}

// class destructor
GD_Terreno::~GD_Terreno()
{
	// insert your code here
}


void GD_Terreno::Crear(char *filenameHMAP,float x, float y, float z)
{
     
    RegistrarDevice(GD_Sistema::device);
    ISceneManager* mismgr=midevice->getSceneManager();
    
    IVideoDriver* driver = midevice->getVideoDriver();
    
	nodt = mismgr->addTerrainSceneNode( filenameHMAP,0,-1, vector3df(0,0,0),vector3df(0,0,0),vector3df(x,y/3,z));

		     
     selector = mismgr->createTerrainTriangleSelector(nodt,0);
	nodt->setTriangleSelector(selector);
	
  nodon =nodt;
    if(!nodon) printf("ERROR: No se pudo Crear Terreno, %s.\n", filenameHMAP); 
     
}

ITriangleSelector* GD_Terreno::RetornarDatos()
{
     return selector;
}

void GD_Terreno::Texturizar(char *filenameTEX)
{
    
     IVideoDriver* driver = midevice->getVideoDriver();
        
     driver->setTextureCreationFlag(video::ETCF_ALWAYS_32_BIT, true);
     driver->setTextureCreationFlag(video::ETCF_CREATE_MIP_MAPS, false);
     
     nodt->setMaterialTexture(0, driver->getTexture(filenameTEX));
     
     driver->setTextureCreationFlag(video::ETCF_ALWAYS_32_BIT, false);
     driver->setTextureCreationFlag(video::ETCF_CREATE_MIP_MAPS, true);
}
